"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToastContextProvider = exports.useToast = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const ToastProviderValues_1 = require("./ToastProviderValues");
const ToastContext = (0, react_1.createContext)({});
const useToast = () => (0, react_1.useContext)(ToastContext);
exports.useToast = useToast;
const ToastContextProvider = ({ children }) => (0, jsx_runtime_1.jsx)(ToastContext.Provider, Object.assign({}, { value: (0, ToastProviderValues_1.ToastProviderValues)() }, { children: children }));
exports.ToastContextProvider = ToastContextProvider;
